config/routes.rb
Hyhull::Application.routes.draw do

  root :to => "pages#home"

  Blacklight.add_routes(self, except: [:catalog, :solr_document])
  match 'resources/opensearch', to: 'catalog#opensearch',  as: 'opensearch_catalog'
  match 'resources/facet/:id', to: 'catalog#facet', as: 'catalog_facet'
  match 'resources', to: 'catalog#index', as: 'catalog_index'
  match 'oai', to: 'catalog#oai', as: 'oai_provider'

  resources :solr_document,  path: 'resources', controller: 'catalog', only: [:show, :update] 
  resources :catalog, path: 'resources', controller: 'catalog', only:  [:show, :update]

  HydraHead.add_routes(self)

  devise_for :users

  mount Hydra::RoleManagement::Engine => '/'
  get "/roles" => 'roles#index'
  resources :profile

  resources :property_types do
    resources :properties
  end
  
  resources :assets
  resources :uketd_objects
  resources :journal_articles
  resources :datasets
  resources :books
  resources :book_chapters

  match 'generic_contents/initial_step', to: 'generic_contents#initial_step', via: [:get]
  resources :generic_contents

  match 'exam_papers/initial_step', to: 'exam_papers#initial_step', via: [:get]
  resources :exam_papers
  
  match 'structural_sets/tree', to: 'structural_sets#tree', via: [:get]
  resources :structural_sets
  match 'structural_sets/:id/update_permissions', to: 'structural_sets#update_permissions', via: [:put]

  match 'display_sets/tree', to: 'display_sets#tree', via: [:get]

  resources :display_sets
  match 'display_sets/:id/update_permissions', to: 'display_sets#update_permissions', via: [:put]
  
  resources :content_metadata
  resources :files
  resources :resource_workflow

  match 'assets/:id/:datastream_id' => 'assets#show'
  match 'assets/map_view/:id/:datastream_id' => 'assets#map_view'

  %w[home about contact cookies takedown].each do |page|
    get page, controller: 'pages', action: page
  end
  match 'healthcheck/rails-status' => 'pages#rails_status'

  authenticate :user do
    mount Hyhull::Resque::AuthorisedResqueServer.new, at: '/resque'
  end

end

app/models/property.rb
# This ActiveRecord::Base class is used to store the Properties for Hyhull
# Property includes the attributes: name, value, property_type
# A property has one PropertyType
class Property < ActiveRecord::Base
  
  attr_accessible :name, :value, :property_type
  belongs_to :property_type 

  validates :name, presence: true
  validates :value, presence: true
  validates :property_type, presence: true  

  validates :name, uniqueness: { scope: :property_type_id }
  validates :value, uniqueness: { scope: :property_type_id }

  # Return a list of Property instances based upon the PropertyType Name
  def self.select_by_property_type_name(property_type_name, sort_by_property_name=true)
    unless property_type_name.blank?
      property_type = PropertyType.where(name: property_type_name)

      unless property_type.empty?
        if sort_by_property_name      
          Property.where(property_type_id: property_type.first.id).order(:name)
        else
          Property.where(property_type_id: property_type.first.id)
        end
      end     

    end
  end

end

app/models/property_type.rb
# This ActiveRecord::Base class is used to store the PropertyType for Hyhull
# PropertyType has a name and description
# Name is generally used in the Property helper for display dropdown selects
class PropertyType < ActiveRecord::Base
  
  has_many :properties 
  attr_accessible :name, :description
  
  validates :name, presence: true
  validates :description, presence: true
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController  
  include Hyhull::Controller::ControllerBehaviour 
  
  def index
    begin
      @property_type = PropertyType.find(params[:property_type_id])
      @properties = @property_type.properties
      @property = Property.new
    rescue Exception => e
      notice = { :alert => "There was an error: #{e}" }
      redirect_to property_types_path, notice
    end
  end

  def edit
    begin
      @property = Property.find(params[:id])
    rescue Exception => e
      notice = { :alert => "There was an error: #{e}" }
      redirect_to property_type_properties_path(params[:property_type_id]), notice
    end
  end

  def update
    begin
      property = Property.find(params[:id])
      property.update_attributes!(params[:property])
      
      if property.save
        notice = { :notice => "Property successfully updated" }
        redirect_to edit_property_type_property_path(id: params[:id]), notice
      end
    rescue Exception => e
      notice = { :alert => "#{e}" }
      redirect_to edit_property_type_property_path(id: params[:id]), notice
    end
  end

  def create
    @property = Property.new(params[:property])
    @property.property_type = PropertyType.find(params[:property_type_id])
    
    if @property.save
      redirect_to property_type_properties_path(params[:property_type_id])
    else
      notice = { :alert => "Could not create property: #{ @property.errors.full_messages.to_sentence }" }
      redirect_to property_type_properties_path(params[:property_type_id]), notice
    end
  end

  def destroy 
    @property = Property.find(params[:id])
    @property.delete
    redirect_to :back
  end

end

app/helpers/property_helper.rb
# PropertyHelper
module PropertyHelper
  # Provides a Select dropdown based upon the proptery_type_name 
  # sort_dropdown is an optional (defaults to true) - Will sort by name..
  def select_by_property_type(form, attribute, property_type_name, sort_dropdown=true, include_blank=true)
    form.input attribute, collection: Property.select_by_property_type_name(property_type_name, sort_dropdown), value_method: "value", include_blank: include_blank
  end
end

app/views/properties/_new.html.erb
<h3>Add a new property</h3>
<%= simple_form_for(@property, url: property_type_properties_path, :html => {:class => 'form-inline' }) do |f| %>
  <%= f.input_field :name, placeholder: "Name" %>
  <%= f.input_field :value, placeholder: "Value" %>
  <%= f.button :submit, "Add" %>
<% end %>

app/views/properties/edit.html.erb
<div class="page-gutter">
  <h2>Property edit <small>- <%= @property.property_type.description %></small></h2>
  <h3><%= @property.name %></h3>
  <p>&nbsp;</p>
  <%= simple_form_for(@property, url: property_type_property_path, :html => {:class => 'form-horizontal' }) do |f| %>
    <%= f.input :name %>
    <%= f.input :value %>
    <%= f.button :submit, "Save" %> 
  <% end %>
  <%= link_to "Back to properties", property_type_properties_path(@property.property_type) %>
</div>

app/views/properties/index.html.erb
<div class="page-gutter">
  <h2>Property edit <small>- <%= @property_type.description %></small></h2>
  <p><strong>Name</strong> is the text that will be displayed in the forms dropdown, <strong>Value</strong> will be text that will be saved into the Resource metadata. Editing the names and values within this list will <strong>not</strong> update the metadata on any pre-existing Resources. In most cases Name and Value should be kept the same for clarity.</p><p>&nbsp</p>

  <div class="row">
    <div class="span12">
      <table class="table table-condensed table-striped table-bordered square-corners">
        <thead>
          <th>Name</th>
          <th>Value</th>
          <th></th>
        </thead>
        <% @properties.each do |property| %>
          <tr>
            <td><%= property.name %></td>
            <td><%= property.value %></td>
            <td><%= link_to "Edit", edit_property_type_property_path(id: property.id) %>&nbsp;&nbsp;<%= link_to image_tag("hyhull/remove.png"), property_type_property_path(id: property.id), method: "delete", :confirm=>"Are you sure you want to delete this property?"  %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
  <%= render partial: "new" %>
  <p>Back to <%= link_to "Property Types", property_types_path %>
</div>