config/routes.rb
Hyhull::Application.routes.draw do

  root :to => "pages#home"

  Blacklight.add_routes(self, except: [:catalog, :solr_document])
  match 'resources/opensearch', to: 'catalog#opensearch',  as: 'opensearch_catalog'
  match 'resources/facet/:id', to: 'catalog#facet', as: 'catalog_facet'
  match 'resources', to: 'catalog#index', as: 'catalog_index'
  match 'oai', to: 'catalog#oai', as: 'oai_provider'

  resources :solr_document,  path: 'resources', controller: 'catalog', only: [:show, :update] 
  resources :catalog, path: 'resources', controller: 'catalog', only:  [:show, :update]

  HydraHead.add_routes(self)

  devise_for :users

  mount Hydra::RoleManagement::Engine => '/'
  get "/roles" => 'roles#index'
  resources :profile

  resources :property_types do
    resources :properties
  end
  
  resources :assets
  resources :uketd_objects
  resources :journal_articles
  resources :datasets
  resources :books
  resources :book_chapters

  match 'generic_contents/initial_step', to: 'generic_contents#initial_step', via: [:get]
  resources :generic_contents

  match 'exam_papers/initial_step', to: 'exam_papers#initial_step', via: [:get]
  resources :exam_papers
  
  match 'structural_sets/tree', to: 'structural_sets#tree', via: [:get]
  resources :structural_sets
  match 'structural_sets/:id/update_permissions', to: 'structural_sets#update_permissions', via: [:put]

  match 'display_sets/tree', to: 'display_sets#tree', via: [:get]

  resources :display_sets
  match 'display_sets/:id/update_permissions', to: 'display_sets#update_permissions', via: [:put]
  
  resources :content_metadata
  resources :files
  resources :resource_workflow

  match 'assets/:id/:datastream_id' => 'assets#show'
  match 'assets/map_view/:id/:datastream_id' => 'assets#map_view'

  %w[home about contact cookies takedown].each do |page|
    get page, controller: 'pages', action: page
  end
  match 'healthcheck/rails-status' => 'pages#rails_status'

  authenticate :user do
    mount Hyhull::Resque::AuthorisedResqueServer.new, at: '/resque'
  end

end

app/controllers/property_types_controller.rb
class PropertyTypesController < ApplicationController
  include Hyhull::Controller::ControllerBehaviour 
  
  def index
    @property_types = PropertyType.all
  end
end

app/views/property_types/index.html.erb
<div class="page-gutter">
  <h2>Hydra at Hull properties</h2>
  <p>The following is a list of property types.  These are used to populate various metadata and resource options within the Hydra at Hull application.</p><p><strong>Note:</strong> These are global properties, adding or removing options will be reflected throughout the application's edit forms.</p>
  <p>&nbsp;</p>

  <div class="row">
    <div class="span12">
      <table class="table table-striped table-bordered square-corners">
        <thead>
          <th>Name</th>
          <th>Description</th>
          <th></th>
        </thead>
        <% @property_types.each do |property_type| %>
          <tr>
            <td><%= property_type.name %></td>
            <td><%= property_type.description %></td>
            <td><%= link_to 'Edit properties', property_type_properties_path(property_type) %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>