config/routes.rb
Hyhull::Application.routes.draw do

  root :to => "pages#home"

  Blacklight.add_routes(self, except: [:catalog, :solr_document])
  match 'resources/opensearch', to: 'catalog#opensearch',  as: 'opensearch_catalog'
  match 'resources/facet/:id', to: 'catalog#facet', as: 'catalog_facet'
  match 'resources', to: 'catalog#index', as: 'catalog_index'
  match 'oai', to: 'catalog#oai', as: 'oai_provider'

  resources :solr_document,  path: 'resources', controller: 'catalog', only: [:show, :update] 
  resources :catalog, path: 'resources', controller: 'catalog', only:  [:show, :update]

  HydraHead.add_routes(self)

  devise_for :users

  mount Hydra::RoleManagement::Engine => '/'
  get "/roles" => 'roles#index'
  resources :profile

  resources :property_types do
    resources :properties
  end
  
  resources :assets
  resources :uketd_objects
  resources :journal_articles
  resources :datasets
  resources :books
  resources :book_chapters

  match 'generic_contents/initial_step', to: 'generic_contents#initial_step', via: [:get]
  resources :generic_contents

  match 'exam_papers/initial_step', to: 'exam_papers#initial_step', via: [:get]
  resources :exam_papers
  
  match 'structural_sets/tree', to: 'structural_sets#tree', via: [:get]
  resources :structural_sets
  match 'structural_sets/:id/update_permissions', to: 'structural_sets#update_permissions', via: [:put]

  match 'display_sets/tree', to: 'display_sets#tree', via: [:get]

  resources :display_sets
  match 'display_sets/:id/update_permissions', to: 'display_sets#update_permissions', via: [:put]
  
  resources :content_metadata
  resources :files
  resources :resource_workflow

  match 'assets/:id/:datastream_id' => 'assets#show'
  match 'assets/map_view/:id/:datastream_id' => 'assets#map_view'

  %w[home about contact cookies takedown].each do |page|
    get page, controller: 'pages', action: page
  end
  match 'healthcheck/rails-status' => 'pages#rails_status'

  authenticate :user do
    mount Hyhull::Resque::AuthorisedResqueServer.new, at: '/resque'
  end

end

app/views/shared/_create_journal_article_icon.html.erb
<div style="padding-top: 0;">
  <a href="/journal_articles/new" title="Deposit a journal article">
    <div class="picture-tile picture-tile-open-access"></div>
  </a>
</div>

app/views/shared/_create_journal_article_tile.html.erb
<div class="row span10 offset1">
  <div class="tile" style="padding-bottom: 0;">
    <h2>
      Open Access publication 
    </h2>
  </div>
</div>
<div class="span7 offset1" >
  <%= render :partial => 'shared/create_journal_article_text' %> 
</div>
<div class="span5">
  <div class="tile" style="padding-top: 0;">
    <p>
      If you have any queries related to the use of Worktribe please use the Comments feature within the system to send a message to the Library.  
    </p>
    <p>
      Queries related to the management of other collections within Hydra can continue to be directed to 
      <%= link_to "repository@hull.ac.uk", 
        "mailto:repository@hull.ac.uk",
        title: "repository@hull.ac.uk" %>.
    </p>
    <p>
      Queries related to the use of open access publishing can continue to be directed to 
      <%= link_to "openaccess@hull.ac.uk", 
        "mailto:openaccess@hull.ac.uk",
        title: "openaccess@hull.ac.uk" %>.  See also guidance on open access available through the Library's 
      <%= link_to "open access libguide", 
        "http://libguides.hull.ac.uk/openaccess",
        title: "open access libguide", target: "_blank" %>.
    </p>
  </div>
</div>
<div class="span2 visible-tablet visible-desktop">
  <%= render :partial => 'shared/create_journal_article_icon' %>
</div>

app/views/shared/_groupQueue_tile.html.erb
<div class="span14 offset1">
  <div class="tile">
    <div class="row-fluid">

      <div class="span16">
            <h2>
                  Group Queues
            </h2>
            <p>
              <%= link_to("YIF Queue", "/resources/?f%5Bis_member_of_ssim%5D%5B%5D=info:fedora/hull:yifQueue&results_view=true") << tag(:br) if yifGroup_user? %>
            </p>
      </div>

    </div>
  </div>
</div>

app/views/shared/_header_navbar.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container container-fluid-fix">
        <a class="btn btn-navbar square-corners" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a> 
        <div class="brand-logo pull-left">
          <%= link_to image_tag("hyhull/hydra_logo_white_transparent_bg.png"), root_path %>
        </div>
        <%= link_to application_name, root_path, :id => "MenuLink", :class => "brand" %>
        <div class="brand-logo pull-right hidden-phone">                  
          <%= link_to image_tag("blah/uoh-logo-white.png"), "http://www.hull.ac.uk", :target => "_blank" %>
        </div>
        <div class="nav-collapse collapse">
          <ul class="nav">
                <%= render :partial=>'/user_util_links' %>
            </ul>
        </div>
    </div>
  </div>
</div>
<% if !(current_page?(controller: '/pages', action: 'home')) %>
  <%= render_search_bar %>
<% end %>

app/views/shared/_home_browse_text.html.erb
<div class="tile">
    <h2>
        Browse <br/><small>You can browse our repository by...</small></h2>

    <p>
    Based on our latest statistics these are currently the most popular searches in the repository. <%= link_to t('blacklight.header_links.login'), new_user_session_path %> to discover the most popular searches for University only content.
    </p>

    <p>
        <%= link_to 'Resource type', '/resources/facet/genre_sim' %><br/>
        <%= link_to 'Subject', '/resources/facet/subject_topic_sim' %><br/>
        <%= link_to 'Creator', '/resources/facet/creator_name_ssim' %>
</div>

app/views/shared/_home_collections_text.html.erb
<div class="tile">
  <h2>
    Collections <br/><small>Have a look at our collections...</small></h2>
  <p>
  </p>
  <p>
    <%= link_to "Collections", "/resources/?f[is_member_of_ssim][]=info:fedora/hull:rootDisplaySet&results_view=true" %>
  </p>
  <p>
  </p>
  <p>
    <%= exam_papers_link %>
  </p>
  <p>
    Submission to the collection of research outputs has now moved to the Worktribe research information system at  
    <%= link_to "https://hull-research.worktribe.com", 
      "https://hull-research.worktribe.com",
      title: "https://hull-research.worktribe.com" %>.
    Please use this system for open access compliance and submission of all other research outputs.
  </p>
</div>

app/views/shared/_home_content_management_text.html.erb
<%# if can?(:create, JournalArticle) %>
  <!-- <div>
    <a href="#">Create a journal article</a>
  </div> -->
<%# end %>

<div class="tile">
  <div class="row-fluid">

      <div class="span4">
        <div class="tile tile-white tile-min-height">
          <% if can?(:create, :all) %>
            <h2>Create</h2>
            <p>
            <%= link_to "Dataset", new_dataset_path %><br/>
            <%= link_to "ETD", new_uketd_object_path %><br/>
            <%= link_to "Examination paper", exam_papers_initial_step_path %><br/>
            <%= link_to "Journal article", new_journal_article_path %><br/>
            <%= link_to "Book", new_book_path %> or <%= link_to "Book chapter", new_book_chapter_path %><br/>
            <%= link_to "Generic content", generic_contents_initial_step_path %><br/>
            </p>
          <% end %>
        </div>
      </div>
      <div class="span4">
        <div class="tile tile-white tile-min-height">
          <% if can?(:tree, StructuralSet) && can?(:tree, DisplaySet) %>
            <h2>Manage</h2>
            <p>
              <%= link_to("Structural sets", structural_sets_tree_path) %><br/>
              <%= link_to("Display sets", display_sets_tree_path) %><br/>
            </p>
          <% end %>
        </div>
      </div>
      <div class="span4">
        <div class="tile tile-white tile-min-height">
          <% if can?(:create, :all) %>
            <h2>Queues</h2>
            <p>
              <%= link_to("Proto Queue", "/resources/?f%5Bis_member_of_ssim%5D%5B%5D=info:fedora/hull:protoQueue&results_view=true") << tag(:br) %>
              <%= link_to("QA Queue", "/resources/?f%5Bis_member_of_ssim%5D%5B%5D=info:fedora/hull:QAQueue&results_view=true") << tag(:br) if contentAccessTeam_user? %>
              <%= link_to("Hidden Queue", "/resources/?f%5Bis_member_of_ssim%5D%5B%5D=info:fedora/hull:hiddenQueue&results_view=true") << tag(:br) if contentAccessTeam_user? %>
              <%= link_to("Deleted Queue", "/resources/?f%5Bis_member_of_ssim%5D%5B%5D=info:fedora/hull:deletedQueue&results_view=true") << tag(:br) if admin_user? %>
              <%= link_to("YIF Queue", "/resources/?f%5Bis_member_of_ssim%5D%5B%5D=info:fedora/hull:yifQueue&results_view=true") << tag(:br) if yifGroup_user? %>
            </p>
          <% end %>
        </div>
      </div>
      <div class="span4">
        <div class="tile tile-white tile-min-height">
          <% if can?(:index, Role) || can?(:index, PropertyType) %>
            <h2>Admin</h2>
            <p>
              <%= link_to("Role Management", roles_path) << tag(:br) if can?(:index, Role) %>       
              <%= link_to("Properties Management", property_types_path) << tag(:br) if can?(:index, PropertyType) %>
            </p>
          <% end %>
        </div>
      </div>
 
    </div>
</div>

app/views/shared/_home_content_management_tile.html.erb
<div class="span14 offset1">  
    <%= render :partial => 'shared/home_content_management_text' %> 
</div>

app/views/shared/_home_help_tile.html.erb
<div class="span7">
	<div class="tile">
	    <h2>
	       Help us help you<br/>
	       <small>
	       Provide us with feedback to enable us to further improve our service to you
	       </small>
	    </h2>
	    <p>
	        <i class="icon-user"></i> Our staff are constantly working to expand the quantity and range of materials available through Hydra.
	    </p>
	    <p>
	        <i class="icon-envelope"></i> Feedback and suggestions for future development and collections are welcome: <%= link_to 'please email Chris Awre', 'mailto:c.awre@hull.ac.uk' %>.
	    </p>
	</div>
</div>

app/views/shared/_home_open_access_icon.html.erb
<div class="tile">
  <a href="mailto:repository@hull.ac.uk?subject=Journal article submission">
    <div class="picture-tile picture-tile-generic"></div>
  </a>
</div>

app/views/shared/_home_university_content_tile.html.erb
<div class="span7 offset1">
  <div class="tile">
    <h2>
        University content<br/>
        <small>
            Sign in to the digital repository for more university content
        </small>
    </h2>
    <p>
        <i class="icon-asterisk"></i> If you are a University of Hull student or member of staff and have not yet signed into Hydra, please do so using the link in the main header bar anytime. <%= link_to t('blacklight.header_links.login'), new_user_session_path %>
    </p>
    <p>
        <i class="icon-asterisk"></i> Use your University User ID and password to sign in (these are the credentials you use to sign into email, eBridge, portal etc)
    </p>
  </div>
</div>

app/views/shared/_pid_namespace.html.erb
<div class="page-gutter">
<div class="row-spacer"></div>
  <%= render "shared/error_messages", :target => resource %>
  <p></p>
  <div class="fields">
    <%= select_by_property_type(f, :pid_namespace, "FEDORA-PID-NAMESPACE", true, false) if admin_user? %>
  </div>
</div>

app/views/shared/_set_select.html.erb
<% # optional params to specify the parent_field_name ie.. UketdObject."parent_id" or DisplaySet.display_set_id, "parent_id"/"display_set_id"  %> 
<% # Resource class is used to specify the source of the tree data ie. StructuralSet/DisplaySet %> 
<% title = "Set membership" if local_assigns[:title].nil? %>
<% parent_field_name = "parent_id" if local_assigns[:parent_field_name].nil? %> 
<% set_class = StructuralSet if local_assigns[:set_class].nil? %>
<% parent_field_id = "#{resource.class.name.underscore}_#{parent_field_name}" %>
<% required = false if local_assigns[:required].nil? %>

<% parent_id = eval("resource.#{parent_field_name}") %>

<% tree_div_id = "#{set_class}-set-tree" %>
<% set_name_field_id = "#{set_class}-set-name"%>
<% set_select_modal_id = "#{set_class}-set-select-modal" %>

<script type="text/javascript">
  $(function() {
    tree_div = "#<%= tree_div_id %>";
    tree_data = [<%= set_class.tree.to_json.html_safe %>];
    selected_id = "<%= parent_id %>";
    self_id = "<%= resource.id %>";
    set_name_target = "#<%= set_name_field_id %>";

    BuildTree(tree_div, tree_data, self_id, selected_id, set_name_target);

  })
</script>


<div class="page-gutter">
  <div class="row-spacer"></div>
    <h6><%= title %></h6>
      <!-- Button to trigger modal -->
      <p>
        <a href="#<%= set_select_modal_id %>" role="button" data-toggle="modal">Edit set membership</a>
      </p>
      <%= form.input :Set, 
        :input_html => {
          :value => "",
          :disabled => true,
          :id => set_name_field_id
      }, required: required %>
      <%= form.input parent_field_name.to_sym, :as => :hidden,
        :input_html => {
          :value => parent_id
        } 
      %>
  <!-- Modal -->
  <div id="<%= set_select_modal_id %>" class="modal hide fade square-corners" tabindex="-1" role="dialog" aria-labelledby="AdditionalMetadataLabel" aria-hidden="true">
    <div class="modal-header">
       <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      <h3>Set selection</h3>
    </div>  
    <div class="modal-body">
      <% if set_class == StructuralSet %>
        <p>Selecting a set from below will give the resource its permissions.</p>
      <% end %>
      <div id="<%= tree_div_id %>"></div>
    </div>
    <div class="modal-footer">
      <button class="btn square-corners" aria-hidden="true" onclick="SelectSet('#<%= tree_div_id %>', '#<%= set_name_field_id %>', '#<%= parent_field_id %>', '#<%= set_select_modal_id %>', <%= required %>)">Select</button>
      <button class="btn square-corners" data-dismiss="modal" aria-hidden="true">Close</button>
    </div>
  </div>
</div>

app/views/shared/_update_resource_state.html.erb
<% # Resources do not have changeable states until they saved... %>
<% if object.persisted? && !object.resource_state.nil? %>
<!--     <h3>Resource workflow</h3> -->
    <div class="pull-left">This resource is currently within the <%= object.human_resource_state_name %> queue</div>  
    <% # Gets the current Resource state queue membership %>
    <% resource_state = object.resource_state  %>

    <% # Get the evailable state events, e.g proto => qa... %>
    <% state_events = object.resource_state_events %>
    <%= form_tag( { controller: :resource_workflow, action: :update, id: params[:id]}, { method: :put, :class => 'pull-right' } ) do |f| %>
      <% state_events.each do |event| %>
        <%= button_tag( object.class.human_resource_state_event_name(event), :type => 'submit', name: :resource_state, :value => event.to_s, :confirm => "Are you sure you want to #{object.class.human_resource_state_event_name(event)}?", class: "btn square-corners") %>
      <% end %>       
    <% end %>

<% end %>