config/routes.rb
Hyhull::Application.routes.draw do

  root :to => "pages#home"

  Blacklight.add_routes(self, except: [:catalog, :solr_document])
  match 'resources/opensearch', to: 'catalog#opensearch',  as: 'opensearch_catalog'
  match 'resources/facet/:id', to: 'catalog#facet', as: 'catalog_facet'
  match 'resources', to: 'catalog#index', as: 'catalog_index'
  match 'oai', to: 'catalog#oai', as: 'oai_provider'

  resources :solr_document,  path: 'resources', controller: 'catalog', only: [:show, :update] 
  resources :catalog, path: 'resources', controller: 'catalog', only:  [:show, :update]

  HydraHead.add_routes(self)

  devise_for :users

  mount Hydra::RoleManagement::Engine => '/'
  get "/roles" => 'roles#index'
  resources :profile

  resources :property_types do
    resources :properties
  end
  
  resources :assets
  resources :uketd_objects
  resources :journal_articles
  resources :datasets
  resources :books
  resources :book_chapters

  match 'generic_contents/initial_step', to: 'generic_contents#initial_step', via: [:get]
  resources :generic_contents

  match 'exam_papers/initial_step', to: 'exam_papers#initial_step', via: [:get]
  resources :exam_papers
  
  match 'structural_sets/tree', to: 'structural_sets#tree', via: [:get]
  resources :structural_sets
  match 'structural_sets/:id/update_permissions', to: 'structural_sets#update_permissions', via: [:put]

  match 'display_sets/tree', to: 'display_sets#tree', via: [:get]

  resources :display_sets
  match 'display_sets/:id/update_permissions', to: 'display_sets#update_permissions', via: [:put]
  
  resources :content_metadata
  resources :files
  resources :resource_workflow

  match 'assets/:id/:datastream_id' => 'assets#show'
  match 'assets/map_view/:id/:datastream_id' => 'assets#map_view'

  %w[home about contact cookies takedown].each do |page|
    get page, controller: 'pages', action: page
  end
  match 'healthcheck/rails-status' => 'pages#rails_status'

  authenticate :user do
    mount Hyhull::Resque::AuthorisedResqueServer.new, at: '/resque'
  end

end

app/controllers/catalog_controller.rb
# -*- encoding : utf-8 -*-
require 'blacklight/catalog'

class CatalogController < ApplicationController
  include BlacklightGoogleAnalytics::ControllerExtraHead
  include Blacklight::Catalog
  include BlacklightOaiProvider::ControllerExtension

  include Hydra::Controller::ControllerBehavior

  # This applies a require login check for the show and index methods - Calls require_login
  # This needs to be applied before enforce_show_permissions to ensure that login redirect is done prior to the auth check. 
  # See ApplicationController
  before_filter :require_login, only: [:show, :index]

  # These before_filters apply the hydra access controls
  before_filter :enforce_show_permissions, only: :show
  # This applies appropriate access controls to all solr queries
  CatalogController.solr_search_params_logic += [:add_access_controls_to_solr_params]
  # This filters out objects that you want to exclude from search results, like FileAssets
  CatalogController.solr_search_params_logic += [:exclude_unwanted_models]


  configure_blacklight do |config|
    config.default_solr_params = { 
      :qt => 'search',
      :rows => 10
    }

    # solr field configuration for search results/index views
    config.index.show_link = 'title_tesim'
    config.index.record_tsim_type = 'active_fedora_model_ssi'

    # solr field configuration for document/show views
    config.show.html_title = 'title_tesim'
    config.show.heading = 'title_tesim'
    config.show.display_type = 'active_fedora_model_ssi'

    # solr fields that will be treated as facets by the blacklight application
    #   The ordering of the field names is the order of the display
    #
    # Setting a limit will trigger Blacklight's 'more' facet values link.
    # * If left unset, then all facet values returned by solr will be displayed.
    # * If set to an integer, then "f.somefield.facet.limit" will be added to
    # solr request, with actual solr request being +1 your configured limit --
    # you configure the number of items you actually want _tsimed_ in a page.    
    # * If set to 'true', then no additional parameters will be sent to solr,
    # but any 'sniffed' request limit parameters will be used for paging, with
    # paging at requested limit -1. Can sniff from facet.limit or 
    # f.specific_field.facet.limit solr request params. This 'true' config
    # can be used if you set limits in :default_solr_params, or as defaults
    # on the solr side in the request handler itself. Request handler defaults
    # sniffing requires solr requests to be made with "echoParams=all", for
    # app code to actually have it echo'd back to see it.  
    #
    # :show may be set to false if you don't want the facet to be drawn in the 
    # facet bookmarked
    config.add_facet_field solr_name('genre', :facetable), :label => 'Resource Type', :limit => 10
    config.add_facet_field solr_name('pub_date', :facetable), :label => 'Publication Year', :limit => 10
    config.add_facet_field solr_name('creator_name', :symbol), :label => 'Creator', :limit => 10
    config.add_facet_field solr_name('creator_organisation_name', :symbol), :label => 'Creator (Organisation)',:limit => 10
    config.add_facet_field solr_name('subject_topic', :facetable), :label => 'Topic', :limit => 10
    config.add_facet_field solr_name('language_text', :facetable), :label => 'Language', :limit => 10
    config.add_facet_field solr_name('department_name', :facetable), :label => 'Department', :limit => 10
    config.add_facet_field solr_name('person_affiliation', :facetable), :label => 'Affiliation', :limit => 10

    # Have BL send all facet field names to Solr, which has been the default
    # previously. Simply remove these lines if you'd rather use Solr request
    # handler defaults, or have no facets.
    config.default_solr_params[:'facet.field'] = config.facet_fields.keys
    #use this instead if you don't want to query facets marked :show=>false
    #config.default_solr_params[:'facet.field'] = config.facet_fields.select{ |k, v| v[:show] != false}.keys


    # solr fields to be displayed in the index (search results) view
    #   The ordering of the field names is the order of the display 
    config.add_index_field solr_name('title_vern', :stored_searchable, type: :string), :label => 'Title:' 
    config.add_index_field solr_name('creator_name', :symbol, type: :string), :label => 'Creator'
    config.add_index_field solr_name('creator_organisation_name', :symbol, type: :string), :label => 'Creator'  
    config.add_index_field solr_name('genre', :displayable, type: :string), :label => 'Resource type'
    config.add_index_field solr_name('subject_topic', :displayable, type: :string), :label => 'Subject'
    config.add_index_field solr_name('language_text', :displayable, type: :string), :label => 'Language'

    config.add_index_field solr_name('author_vern', :stored_searchable, type: :string), :label => 'Author:' 
    config.add_index_field solr_name('format', :symbol), :label => 'Format:' 
    config.add_index_field solr_name('published', :stored_searchable, type: :string), :label => 'Published:'
    config.add_index_field solr_name('published_vern', :stored_searchable, type: :string), :label => 'Published:'
    config.add_index_field solr_name('lc_callnum', :stored_searchable, type: :string), :label => 'Call number:'

    # solr fields to be displayed in the show (single result) view
    #   The ordering of the field names is the order of the display 
    config.add_show_field solr_name('contributor_name', :displayable, type: :string), :label => 'Contributor'  
    config.add_show_field solr_name('rights', :displayable, type: :string), :label => 'Rights'
    config.add_show_field solr_name('title_vern', :stored_searchable, type: :string), :label => 'Title'
    config.add_show_field solr_name('author_vern', :stored_searchable, type: :string), :label => 'Author:' 
    config.add_show_field solr_name('format', :symbol), :label => 'Format:' 
    config.add_show_field solr_name('url_fulltext_tsim', :stored_searchable, type: :string), :label => 'URL:'
    config.add_show_field solr_name('url_suppl_tsim', :stored_searchable, type: :string), :label => 'More Information:'
    config.add_show_field solr_name('language', :stored_searchable, type: :string), :label => 'Language:'
    config.add_show_field solr_name('published', :stored_searchable, type: :string), :label => 'Published:'
    config.add_show_field solr_name('published_vern', :stored_searchable, type: :string), :label => 'Published:'
    config.add_show_field solr_name('lc_callnum', :stored_searchable, type: :string), :label => 'Call number:'
    config.add_show_field solr_name('isbn', :stored_searchable, type: :string), :label => 'ISBN:'



    # "fielded" search configuration. Used by pulldown among other places.
    # For supported keys in hash, see rdoc for Blacklight::SearchFields
    #
    # Search fields will inherit the :qt solr request handler from
    # config[:default_solr_parameters], OR can specify a different one
    # with a :qt key/value. Below examples inherit, except for subject
    # that specifies the same :qt as default for our own internal
    # testing purposes.
    #
    # The :key is what will be used to identify this BL search field internally,
    # as well as in URLs -- so changing it after deployment may break bookmarked
    # urls.  A display label will be automatically calculated from the :key,
    # or can be specified manually to be different. 

    # This one uses all the defaults set by the solr request handler. Which
    # solr request handler? The one set in config[:default_solr_parameters][:qt],
    # since we aren't specifying it otherwise. 
    
    config.add_search_field 'all_fields', :label => 'All Fields'
    

    # Now we see how to over-ride Solr request handler defaults, in this
    # case for a BL "search field", which is really a dismax aggregate
    # of Solr search fields. 
    
    config.add_search_field('title') do |field|
      # solr_parameters hash are sent to Solr as ordinary url query params. 
      #field.solr_parameters = { :'spellcheck.dictionary' => 'title' }

      # :solr_local_parameters will be sent using Solr LocalParams
      # syntax, as eg {! qf=$title_qf }. This is neccesary to use
      # Solr parameter de-referencing like $title_qf.
      # See: http://wiki.apache.org/solr/LocalParams
      field.solr_local_parameters = { 
        :qf => '$title_qf',
        :pf => '$title_pf'
      }
    end
    
    config.add_search_field('creator') do |field|
      #field.solr_parameters = { :'spellcheck.dictionary' => 'author' }
      field.solr_local_parameters = { 
        :qf => '$creator_qf',
        :pf => '$creator_pf'
      }
    end
    
    # Specifying a :qt only to show it's possible, and so our internal automated
    # tests can test it. In this case it's the same as 
    # config[:default_solr_parameters][:qt], so isn't actually neccesary. 
    config.add_search_field('subject') do |field|
      #field.solr_parameters = { :'spellcheck.dictionary' => 'subject' }
      field.qt = 'search'
      field.solr_local_parameters = { 
        :qf => '$subject_qf',
        :pf => '$subject_pf'
      }
    end

    # "sort results by" select (pulldown)
    # label in pulldown is followed by the name of the SOLR field to sort by and
    # whether the sort is ascending or descending (it must be asc or desc
    # except in the relevancy case).
    config.add_sort_field 'score desc, sortable_date_dtsi desc, title_ssort asc', :label => 'relevance'
    config.add_sort_field 'sortable_date_dtsi desc, title_ssort asc', :label => 'year'
    config.add_sort_field 'creator_name_ssort asc, title_ssort asc', :label => 'author'
    config.add_sort_field 'title_ssort asc, sortable_date_dtsi desc', :label => 'title'

    # If there are more than this many search results, no spelling ("did you 
    # mean") suggestion is offered.
    config.spell_max = 5

    config.oai = {

app/views/catalog/_book_fields.html.erb
<div class="row">
  <hr/>
  <div class="span4">
    <%= display_resource_thumbnail(document) %>
  </div>

  <div class="span12">
    <%# default partial to display solr document fields in catalog show view -%>
    <dl class="dl-vertical-left dl-invert">
      <% document_show_fields(document).each do |solr_fname, field| -%>
        <% if should_render_show_field? document, field %>
          <dt class="blacklight-<%= solr_fname.parameterize %>"><%= render_document_show_field_label document, :field => solr_fname %></dt>
          <dd class="blacklight-<%= solr_fname.parameterize %>"><%= render_document_show_field_value document, :field => solr_fname %></dd>
        <% end -%>
      <% end %>

      <%= display_text_area_field(document, 'description_ssm', 'Description', 'description_ssm') %>
      <%= display_field(document, 'publisher_ssm', 'Publisher', 'publisher_ssm') %>
      <%= display_boolean_field(document, 'peer_reviewed_ssm', 'Peer reviewed', 'peer_reviewed_ssm') %>
      <%= display_field(document, 'language_text_ssm', 'Language', 'language_text_ssm') %>
      <%= display_field(document, 'citation_ssm', 'Citation', 'citation_ssm') %>
      <%= display_field(document, 'doi_ssm', 'DOI', 'doi_ssm') %> 
      <%= display_field(document, 'additional_notes_ssm', 'Additional notes', 'additional_notes_ssm') %>
      <%= display_field(document, 'extent_ssm', 'Extent', 'extent_ssm') %>
      <%= display_field(document, 'id', 'Identifier', 'id') %> 
    </dl>

    <h3>Publication information</h3>
    <dl class="dl-horizontal dl-invert">
      <%= display_date_field(document, 'related_item_publication_date_ssm', 'Publication date', 'related_item_publication_date_ssm') %>
      <%= display_field(document, 'related_item_publisher_ssm', 'Publisher', 'publication_publisher_ssm') %>
      <%= display_field(document, 'related_item_place_ssm', 'Place', 'publication_place_ssm') %>
      <%= display_field(document, 'related_item_physical_extent_ssm', 'Physical extent', 'related_item_physical_extent_ssm') %>      
      <%= doi_resolver_field(document, 'related_item_doi_ssm', 'DOI', 'related_item_article_doi_ssm') %>
      <%= display_field(document, 'related_item_print_issn_ssm', 'ISSN (Print)', 'related_item_print_issn_ssm') %>
      <%= display_field(document, 'related_item_electronic_issn_ssm', 'ISSN (Electronic)', 'related_item_electronic_issn_ssm') %>
      <%= display_field(document, 'related_item_isbn_ssm', 'ISBN', 'related_item_isbn_ssm') %>
      <%= display_field(document, 'related_item_volume_ssm', 'Volume', 'related_item_volume_ssm') %>
      <%= display_field(document, 'related_item_issue_ssm', 'Issue', 'related_item_issue_ssm') %>
      <%= display_field(document, 'related_item_start_page_ssm', 'Start page', 'related_item_start_page_ssm') %>
      <%= display_field(document, 'related_item_end_page_ssm', 'End page', 'related_item_end_page_ssm') %>
      <%= display_field(document, 'related_item_restriction_ssm', 'Restriction', 'related_item_restriction_ssm') %>
      <%= display_field(document, 'related_web_url_ssm', 'Related web materials', 'related_web_url_ssm') %> 
      <%= display_field(document, 'see_also_ssm', 'See also', 'see_also_ssm') %> 
    </dl>

  </div>
</div>

app/views/catalog/_constraints_element.erb
<%- # local params:
    # label
    # value
    # options =>
    # :remove => url for a remove constraint link
    # :classes => array of classes to add to container span
    options ||= {}
    options[:escape_label] = true unless options.has_key?(:escape_label)
    options[:escape_value] = true unless options.has_key?(:escape_value)
-%>
<span class="appliedFilter constraint <%= options[:classes].join(" ") if options[:classes] %>">
  <%- unless label.blank? -%>
    <span class="filterName"><%= options[:escape_label] ? h(label) : raw(label) %></span>
  <%- end -%>
  <%- unless value.blank? -%>
    <span class="filterValue"><%= options[:escape_value] ? h(value) : raw(value) %></span>
  <%- end -%>
  <%- unless options[:remove].blank? -%>
    <% accessible_remove_label =
            if label.blank?
              t('blacklight.search.filters.remove.value', :value => (options[:escape_value] ? h(value) : value))
            else
              t('blacklight.search.filters.remove.label_value', :label => (options[:escape_label] ? h(label) : label), :value => (options[:escape_value] ? h(value) : value))
            end
    %>
    <%= link_to(accessible_remove_label.html_safe, options[:remove], :class=>'btnRemove imgReplace') %>
  <%- end -%>
</span>

app/views/catalog/_document_list.html.erb
<% # container for all documents in index view -%>
<div id="documents">
  <%= render documents, :as => :document %>
</div>

app/views/catalog/_facet_pagination.html.erb
      <span class="prev_next_links btn-group pull-left">
        <%= link_to_previous_page @pagination, raw(t('views.pagination.previous')), :params => params, :param_name => Blacklight::Solr::FacetPaginator.request_keys[:page], :class => 'btn' do %>
         <span class="disabled btn"><%= raw(t('views.pagination.previous')) %></span>
       <% end %>
        <%= link_to_next_page @pagination, raw(t('views.pagination.next')), :params => params, :param_name => Blacklight::Solr::FacetPaginator.request_keys[:page], :class => 'btn' do %>
         
         <span class="disabled btn"><%= raw(t('views.pagination.next')) %></span>
        <% end %>
      </span>

      <span class="sort_options btn-group pull-right">
        <% if @pagination.sort == 'index' -%>
          <span class="active az btn"><%= t('blacklight.search.facets.sort.index') %></span><%= link_to_unless(@pagination.sort == 'count', t('blacklight.search.facets.sort.count'), 
            @pagination.params_for_resort_url('count', params), :class => "sort_change numeric btn") %>
        <% elsif @pagination.sort == 'count' -%>
          <%=  link_to(t('blacklight.search.facets.sort.index'), @pagination.params_for_resort_url('index', params), 
            :class => "sort_change az btn") %><span class="active numeric btn"><%= t('blacklight.search.facets.sort.count') %></span>
        <% end -%>    
      </span>
    </div>

app/views/catalog/_index_default.html.erb
<%# default partial to display solr document fields in catalog index view -%>
<dl class="document-metadata dl-horizontal-left  dl-invert">
  <% index_fields(document).each do |solr_fname, field| -%>
    <% if should_render_index_field? document, field %>
	    <dt class="blacklight-<%= solr_fname.parameterize %>"><%= render_index_field_label document, :field => solr_fname %></dt>
	    <dd class="blacklight-<%= solr_fname.parameterize %>"><%= render_index_field_value document, :field => solr_fname %></dd>
    <% end -%>
  <% end -%>
</dl>

app/views/catalog/_per_page_widget.html.erb
<% if show_sort_and_per_page? and !blacklight_config.per_page.blank? %>
<div id="per_page-dropdown" class="dropdown pull-right  hidden-phone">
  <span class="hide-text"><%= t('blacklight.search.per_page.title') %></span>
  <ul class="css-dropdown">
    <li class="btn btn-small square-corners">
      <%= link_to(t(:'blacklight.search.per_page.button_label', :count => current_per_page), "#") %> <span class="caret"></span>
      <ul>
        <%- blacklight_config.per_page.each do |count| %>
          <li><%= link_to(t(:'blacklight.search.per_page.label', :count => count).html_safe, url_for(params_for_search(:per_page => count))) %></li>
        <%- end -%>
      </ul>
    </li>
  </ul>
</div>
<% end %>

app/views/catalog/_results_pagination.html.erb
<% if paginate_params(@response).num_pages > 1 %>
 <div class="row record-padding">
  <div class="span16 hidden-phone">
    <div class="pagination">
      <%= paginate_rsolr_response @response, :outer_window => 2, :theme => 'blacklight' %>
    </div>
  </div>
 </div>
<% end %>

app/views/catalog/_search_form.html.erb
<div class="subnav navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container container-fluid-fix">
      <div class="row-fluid">
          <div class="subnav-position">

            <%= form_tag catalog_index_path, :method => :get, :class => 'form-inline form-search form-sub-search'  do %>

            <div class="input-prepend input-append">

              <%= search_as_hidden_fields(:omit_keys => [:q, :search_field, :qt, :page]).html_safe %> 

              <% unless search_fields.empty? %>
                <%= select_tag(:search_field, options_for_select(search_fields, h(params[:search_field])), :title => t('blacklight.search.form.search_field.title'), :class=>"search-field square-corners input-medium") %>
              <% end %>

              <%= text_field_tag :q, params[:q], :class =>  "q input-xlarge search-query square-corners", :placeholder => 'Search the repository...' %>

              <button class="btn square-corners" name="button" type="submit"><i class="icon-search icon hidden-phone"></i> Search</button>
 
            </div>
            <span class="hidden-phone">
              <span class="vertical-divider hidden-phone"></span>
              <%#= link_to 'Advanced search', params.merge(:controller=>"advanced", :action=>"index") , :class=>"advanced_search row-spacer"%>
            </span>

            <div class="visible-phone">
              <hr style="margin-bottom: 10px;"/>
              <span>
                <%#= link_to 'Advanced search', params.merge(:controller=>"advanced", :action=>"index") , :class=>"advanced_search row-spacer"%>
              </span>              
            </div>  
                     
          </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/catalog/_show_exam_paper.html.erb
<%# Sub header display fields %>
<%= display_field_within_element(document, 'module_display_ssm', element='h3') %>
<%= display_field_within_element(document, 'date_issued_ssm', element='h6', :date_field => true) %>
<%= display_field_within_element(document, 'department_name_ssm', element='h6') %>
<%= display_field_within_element(document, 'genre_ssm', element='p') %>

<div class="row">
  <hr/>
  <div class="span4">
    <%= display_resource_thumbnail(document) %>
  </div>
  <div class="span12">  
    <%# default partial to display solr document fields in catalog show view -%>
    <dl class="dl-vertical-left dl-invert">
      <%= display_field(document, 'exam_level_ssm', 'Exam level', 'exam_level_ssm') %>
      <%= display_field(document, 'subject_topic_ssm', 'Subject', 'subject_topic_ssm') %>

      <% document_show_fields(document).each do |solr_fname, field| -%>
    	  <% if should_render_show_field? document, field %>
          <dt class="blacklight-<%= solr_fname.parameterize %>"><%= render_document_show_field_label document, :field => solr_fname %></dt>
    	    <dd class="blacklight-<%= solr_fname.parameterize %>"><%= render_document_show_field_value document, :field => solr_fname %></dd>
    	  <% end -%>
      <% end -%>
      <%= display_text_area_field(document, 'additional_notes_ssm', 'Additional information', 'additional_notes_ssm') %>
      <%= display_field(document, 'publisher_ssm', 'Publisher', 'publisher_ssm') %>
      <%= display_field(document, 'genre_ssm', 'Resource type', 'genre_ssm') %>
      <%= display_field(document, 'language_text_ssm', 'Language', 'language_text_ssm') %>
      <%= display_field(document, 'extent_ssm', 'Extent', 'extent_ssm') %>
      <%= display_field(document, 'id', 'Identifier', 'id') %>
    </dl>
  </div>
</div>

app/views/catalog/_show_journal_article.html.erb
<%# Sub header display fields %>
<%= display_field_within_element(document, 'creator_name_ssim', element='h3') %>
<%= display_field_within_element(document, 'name_affiliation_ssm', element='h6') %>
<%= display_field_within_element(document, 'subject_topic_ssm', element='h6') %>
<%= display_field_within_element(document, 'journal_publication_date_ssm', element='h6', :date_field => true) %>
<%= display_field_within_element(document, 'genre_ssm', element='p') %>

<div class="row">
  <hr/>
  <div class="span4">
    <%= display_resource_thumbnail(document) %>
  </div>

  <div class="span12">
    <%# default partial to display solr document fields in catalog show view -%>
    <dl class="dl-vertical-left dl-invert">
      <% document_show_fields(document).each do |solr_fname, field| -%>
        <% # We filter the creatpr out, because it is being displayed above with label author %>
        <% unless field.label.downcase == "creator" %>
    	    <% if should_render_show_field? document, field %>
            <dt class="blacklight-<%= solr_fname.parameterize %>"><%= render_document_show_field_label document, :field => solr_fname %></dt>
    	      <dd class="blacklight-<%= solr_fname.parameterize %>"><%= render_document_show_field_value document, :field => solr_fname %></dd>
    	    <% end -%>
    	  <% end %>
      <% end -%>
      <%= display_field(document, 'title_alternative_tesim', 'Alternative title', 'title_alternative_tesim') %>
      <%= display_text_area_field(document, 'abstract_ssm', 'Abstract', 'abstract_ssm') %>
      <%= display_field(document, 'publisher_ssm', 'Publisher', 'publisher_ssm') %>
      <%= display_boolean_field(document, 'peer_reviewed_ssm', 'Peer reviewed', 'peer_reviewed_ssm') %>
      <%= display_field(document, 'language_text_ssm', 'Language', 'language_text_ssm') %>
      <%= display_field(document, 'extent_ssm', 'Extent', 'extent_ssm') %>
      <%= display_field(document, 'id', 'Identifier', 'id') %>
    </dl>
    <h3>Journal</h3>

    <dl class="dl-vertical-left dl-invert">
      <%= display_field(document, 'journal_title_ssm', 'Journal title', 'journal_title_ssm') %>
      <%= display_date_field(document, 'journal_publication_date_ssm', 'Publication date', 'journal_publication_date_ssm') %>
      <%= display_field(document, 'journal_publisher_ssm', 'Publisher', 'journal_publisher_ssm') %>
      <%= doi_resolver_field(document, 'journal_article_doi_ssm', 'DOI', 'journal_article_doi_ssm') %>
      <%= display_field(document, 'journal_print_issn_ssm', 'ISSN (Print)', 'journal_print_issn_ssm') %>
      <%= display_field(document, 'journal_electronic_issn_ssm', 'ISSN (Electronic)', 'journal_electronic_issn_ssm') %>
      <%= display_field(document, 'journal_volume_ssm', 'Volume', 'journal_volume_ssm') %>
      <%= display_field(document, 'journal_issue_ssm', 'Issue', 'journal_issue_ssm') %>
      <%= display_field(document, 'journal_start_page_ssm', 'Start page', 'journal_start_page_ssm') %>
      <%= display_field(document, 'journal_end_page_ssm', 'End page', 'journal_end_page_ssm') %>
      <%= display_field(document, 'journal_article_restriction_ssm', 'Restriction', 'journal_article_restriction_ssm') %>
      <%= display_text_area_field(document, 'journal_publications_note_ssm', 'Notes', 'notes_publications_ssm') %>
      <%= display_related_urls(document, 'journal_url_ssm', "Link" ,"journal_url_display_label_ssm", 'journal_url_ssm' ) %>
    </dl>
  </div>

</div>

app/views/catalog/_show_sidebar.html.erb
<div class="well square-corners" id="sidebar-nav">
  <%= render :partial => 'show_assets' %>
</div><!--/well -->

 <%#= render :partial => 'show_tools' %>
  
<% unless @document.more_like_this.empty? %>
<div class="well" id="sidebar-mlt">
  <ul class="nav nav-list">
  <li class="nav-header">More Like This</li>
    <%= render :collection => @document.more_like_this, :partial => 'show_more_like_this', :as => :document %>
  </ul>
</div><!--/well -->
<% end %>

app/views/catalog/_show_tools.html.erb
  <%-
  # Compare with render_document_functions_partial helper, and
  # _document_functions partial. BL actually has two groups
  # of document-related tools. "document functions" by default
  # contains Bookmark functionality shown on both results and
  # item view. While "document tools" contains external export type
  # functions by default only on detail.

  #Added Bootstrap class well and 'hidden-phone' for the tools-bar 
-%>
<div class="tools-nav pull-left">  
  <%= render :partial => 'qr_code' %>
</div>
<div class="btn-group pull-left">
  <a class="btn dropdown-toggle square-corners" data-toggle="dropdown" href="#">
    Metadata
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu square-corners">
    <li class="mods">
      <%= link_to "MODS", asset_path(:id => @document.id, :datastream_id => "descMetadata") %>
    </li>
    <li>
       <%= link_to "Dublin Core", "#{catalog_path(:id => @document.id)}.oai_dc_xml" %>
    </li>
    <% # Only ETDs have UKETD-DC metadata %> 
    <% if model_from_document(@document) == "UketdObject" %>
      <li class="uketd_dc">
        <%= link_to "UKETD-DC",  "#{catalog_path(:id => @document.id)}.uketd_dc_xml" %>
      </li>
    <% end %>
  </ul>
</div>

app/views/catalog/_sort_and_per_page.html.erb
<div id="sortAndPerPage">

   <div class="page_links">
     <h3>Results <small><%= render :partial => "paginate_compact" %></small>
     </h3>
   </div>
    <%= render :partial => 'sort_widget' %>

    <%= render :partial => 'per_page_widget' %>

</div>

app/views/catalog/_sort_widget.html.erb
<% if show_sort_and_per_page? and !blacklight_config.sort_fields.blank? %>
<div id="sort-dropdown" class="dropdown pull-right hidden-phone">
  <ul class="css-dropdown">
    <li class="btn btn-small square-corners">
      <%= link_to(t('blacklight.search.sort.label', :field =>current_sort_field.label), "#") %> <span class="caret"></span>
      <ul>
        <%- blacklight_config.sort_fields.each do |sort_key, field| %>
          <li><%= link_to(field.label, url_for(params_for_search(:sort => sort_key))) %></li>
        <%- end -%>
      </ul>
    </li>
  </ul>
</div>
<% end %>